/* Generated By:JavaCC: Do not edit this line. HTMLConstants.java */
package HTMLMJZ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HTMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int create = 2;
  /** RegularExpression Id. */
  int elem = 3;
  /** RegularExpression Id. */
  int img = 4;
  /** RegularExpression Id. */
  int head = 5;
  /** RegularExpression Id. */
  int para = 6;
  /** RegularExpression Id. */
  int url = 7;
  /** RegularExpression Id. */
  int quote = 8;
  /** RegularExpression Id. */
  int phrase = 9;
  /** RegularExpression Id. */
  int text = 10;
  /** RegularExpression Id. */
  int color = 11;
  /** RegularExpression Id. */
  int font = 12;
  /** RegularExpression Id. */
  int SPACE = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "<create>",
    "<elem>",
    "<img>",
    "\"HEADING\"",
    "\"PARAGRAPH\"",
    "\"LINK\"",
    "<quote>",
    "<phrase>",
    "<text>",
    "<color>",
    "<font>",
    "<SPACE>",
  };

}
