/* Generated By:JavaCC: Do not edit this line. HTMLConstants.java */
package HTMLMJZ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HTMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int quote = 5;
  /** RegularExpression Id. */
  int sentence = 6;
  /** RegularExpression Id. */
  int alphanum = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<quote>",
    "<sentence>",
    "<alphanum>",
    "\"ADD\"",
    "\"IMAGE WITH SOURCE\"",
    "\"HEADING\"",
  };

}
